# Generated by Django 3.0.3 on 2020-02-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('grade', models.CharField(max_length=1)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
